name: Build and Release

on:
  push:
    tags:
      - '**'

jobs:
  build:
    name: Export to Asset-lib
    env:

        # Version must include major, minor, and patch, and be >= 4.0.0
        # Pre-release label is optional.
        # also valid: 4.0.0.rc1 or 4.0.0, etc
        GODOT_ASSET_ID: 438
        #Use XogotID if it isn't imported from Godot Asset Library
        # XODOT_ASSET_ID: 0
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - uses: chickensoft-games/setup-godot@v1
      name: 🤖 Setup Godot
      with:
          version: ${{vars.GODOT_VERSION}}
          use-dotnet: false
          include-templates: false

    - name: import project
      run: godot --headless -e --quit-after 100
    - name: Zip up Folder
      run: zip -r build.zip . -x "*.git*" -x "*.github*" -x "*.vscode*" -x ".godot/editor/*" -x "build.zip"

    - name: Upload Zip
      run: |
        RESPONSE=$(curl --data-binary "@build.zip" \
            "${{secrets.uploadUrl}}?godot_id=${{env.GODOT_ASSET_ID}}&xodot_id=${{env.XODOT_ASSET_ID}}&version=${{ github.ref_name }}" \
            -H "apiKey: ${{secrets.apiKey}}")
        if [ $? -eq 0 ]; then
          echo "SUCCESS"
        else
          echo "FAILURE"
          exit 1
        fi